//! Build script to generate the asset registry by scanning for WASM files.
//!
//! This scans `target/wasm32-unknown-unknown/release/` for known model and operator
//! WASM files and generates Rust code that embeds them using `include_bytes!()`.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Known model crate names
const MODELS: &[(&str, &str)] = &[
    ("simple_sphere_model", "Simple Sphere"),
    ("simple_torus_model", "Simple Torus"),
    ("rounded_box_model", "Rounded Box"),
    ("gyroid_lattice_model", "Gyroid Lattice"),
    ("mandelbulb_model", "Mandelbulb"),
];

/// Known operator crate names
const OPERATORS: &[(&str, &str)] = &[
    ("boolean_operator", "Boolean"),
    ("translate_operator", "Translate"),
    ("rotation_operator", "Rotation"),
    ("scale_operator", "Scale"),
    ("lua_script_operator", "Lua Script"),
    ("stl_import_operator", "STL Import"),
];

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // The workspace root is two levels up from crates/volumetric_assets
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let wasm_dir = workspace_root
        .join("target")
        .join("wasm32-unknown-unknown")
        .join("release");

    let include_models = env::var("CARGO_FEATURE_MODELS").is_ok();
    let include_operators = env::var("CARGO_FEATURE_OPERATORS").is_ok();

    let mut code = String::new();

    // Generate model constants
    code.push_str("// Auto-generated by build.rs - do not edit\n\n");

    if include_models {
        code.push_str("/// Bundled model assets\n");
        code.push_str("pub const BUNDLED_MODELS: &[BundledAsset] = &[\n");

        for (name, display_name) in MODELS {
            let wasm_path = wasm_dir.join(format!("{}.wasm", name));
            if wasm_path.exists() {
                println!("cargo:rerun-if-changed={}", wasm_path.display());
                code.push_str(&format!(
                    "    BundledAsset {{\n        name: \"{}\",\n        display_name: \"{}\",\n        bytes: include_bytes!(\"{}\"),\n        category: AssetCategory::Model,\n    }},\n",
                    name,
                    display_name,
                    wasm_path.display()
                ));
            } else {
                println!(
                    "cargo:warning=WASM file not found: {}. Model '{}' will not be bundled.",
                    wasm_path.display(),
                    name
                );
            }
        }

        code.push_str("];\n\n");
    } else {
        code.push_str("/// Bundled model assets (disabled)\n");
        code.push_str("pub const BUNDLED_MODELS: &[BundledAsset] = &[];\n\n");
    }

    if include_operators {
        code.push_str("/// Bundled operator assets\n");
        code.push_str("pub const BUNDLED_OPERATORS: &[BundledAsset] = &[\n");

        for (name, display_name) in OPERATORS {
            let wasm_path = wasm_dir.join(format!("{}.wasm", name));
            if wasm_path.exists() {
                println!("cargo:rerun-if-changed={}", wasm_path.display());
                code.push_str(&format!(
                    "    BundledAsset {{\n        name: \"{}\",\n        display_name: \"{}\",\n        bytes: include_bytes!(\"{}\"),\n        category: AssetCategory::Operator,\n    }},\n",
                    name,
                    display_name,
                    wasm_path.display()
                ));
            } else {
                println!(
                    "cargo:warning=WASM file not found: {}. Operator '{}' will not be bundled.",
                    wasm_path.display(),
                    name
                );
            }
        }

        code.push_str("];\n\n");
    } else {
        code.push_str("/// Bundled operator assets (disabled)\n");
        code.push_str("pub const BUNDLED_OPERATORS: &[BundledAsset] = &[];\n\n");
    }

    // Write generated code
    let out_path = out_dir.join("asset_registry.rs");
    fs::write(&out_path, code).expect("Failed to write asset_registry.rs");

    // Rerun if the wasm directory changes
    println!("cargo:rerun-if-changed={}", wasm_dir.display());
}
