//! Build script to generate the asset registry by scanning for WASM files.
//!
//! This scans `target/wasm32-unknown-unknown/release/` for known model and operator
//! WASM files and generates Rust code that embeds them using `include_bytes!()`.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Known model crate names
const MODELS: &[(&str, &str)] = &[
    ("simple_sphere_model", "Simple Sphere"),
    ("simple_torus_model", "Simple Torus"),
    ("rounded_box_model", "Rounded Box"),
    ("gyroid_lattice_model", "Gyroid Lattice"),
    ("mandelbulb_model", "Mandelbulb"),
    // A solid cube with an x-gradient density channel — the lattice
    // operator's playground input.
    ("density_gradient_model", "Density Gradient"),
];

/// Known operator crate names
const OPERATORS: &[(&str, &str)] = &[
    ("boolean_operator", "Boolean"),
    ("translate_operator", "Translate"),
    ("rotation_operator", "Rotation"),
    ("scale_operator", "Scale"),
    ("lua_script_operator", "Lua Script"),
    ("stl_import_operator", "STL Import"),
    ("rectangular_prism_operator", "Rectangular Prism"),
    ("heightmap_extrude_operator", "Heightmap Extrude"),
    ("image_model_operator", "Image"),
    ("extrude_operator", "Extrude"),
    ("revolve_operator", "Revolve"),
    ("fea_grid_mesh_operator", "FEA Grid Mesh"),
    ("fea_solve_operator", "FEA Solve"),
    ("fea_density_operator", "FEA Density"),
    ("fea_inverse_operator", "FEA Inverse"),
    ("fea_deform_operator", "FEA Deform"),
    ("mesh_to_model_operator", "Mesh to Model"),
    ("mesh_height_operator", "Mesh Height Query"),
    ("lattice_operator", "Lattice"),
    ("strut_pattern_operator", "Strut Pattern"),
    ("strut_model_operator", "Strut Model"),
    ("brim_operator", "Brim"),
    ("subspace_operator", "Subspace"),
    ("model_bound_operator", "Model Bound"),
    ("slice_operator", "Slice"),
];

/// Reads `version = "..."` from a bundled crate's Cargo.toml. Every bundled
/// asset declares `version: env!("CARGO_PKG_VERSION")` in its metadata, so
/// the manifest version IS the declared metadata version — bundling it lets
/// consumers (e.g. the UI's upgrade offer) know bundled versions without
/// compiling the wasm modules at runtime.
fn crate_version(crate_dir: &std::path::Path) -> String {
    let manifest = crate_dir.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let text = fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));
    text.lines()
        .find_map(|line| {
            line.strip_prefix("version")?
                .trim_start()
                .strip_prefix('=')?
                .trim()
                .strip_prefix('"')?
                .strip_suffix('"')
                .map(str::to_string)
        })
        .unwrap_or_else(|| panic!("no version in {}", manifest.display()))
}

/// Reports a missing wasm artifact. Normally a warning (dev builds often
/// don't need the bundle — tests, check builds), but release packaging must
/// not silently ship an empty library: with VOLUMETRIC_ASSETS_REQUIRE set
/// (the daemon Containerfile sets it), a missing file fails the build.
fn missing(wasm_path: &std::path::Path, kind: &str, name: &str) {
    if env::var_os("VOLUMETRIC_ASSETS_REQUIRE").is_some() {
        panic!(
            "{kind} '{name}' not found at {} but VOLUMETRIC_ASSETS_REQUIRE is set — run `cargo build-wasm` first",
            wasm_path.display()
        );
    }
    println!(
        "cargo:warning=WASM file not found: {}. {kind} '{name}' will not be bundled.",
        wasm_path.display()
    );
}

fn main() {
    println!("cargo:rerun-if-env-changed=VOLUMETRIC_ASSETS_REQUIRE");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // The workspace root is two levels up from crates/volumetric_assets
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let wasm_dir = workspace_root
        .join("target")
        .join("wasm32-unknown-unknown")
        .join("release");

    let include_models = env::var("CARGO_FEATURE_MODELS").is_ok();
    let include_operators = env::var("CARGO_FEATURE_OPERATORS").is_ok();

    let mut code = String::new();

    // Generate model constants
    code.push_str("// Auto-generated by build.rs - do not edit\n\n");

    // Everything here is `static`, never `const`: a const's promoted
    // allocation is materialized at every use site, so `const` registries
    // duplicated every include_bytes!() blob once per referencing function
    // (measured: +73MB on the web bundle — the whole 36.5MB library twice).
    let mut emit = |kind: &str, subdir: &str, list: &[(&str, &str)], enabled: bool| {
        let array_name = format!("BUNDLED_{}S", kind.to_uppercase());
        if !enabled {
            code.push_str(&format!(
                "/// Bundled {} assets (disabled)\npub static {array_name}: &[BundledAsset] = &[];\n\n",
                kind.to_lowercase()
            ));
            return;
        }
        let mut entries = String::new();
        for (name, display_name) in list {
            let wasm_path = wasm_dir.join(format!("{}.wasm", name));
            if wasm_path.exists() {
                println!("cargo:rerun-if-changed={}", wasm_path.display());
                let version = crate_version(&workspace_root.join(subdir).join(name));
                let bytes_static = format!("{}_BYTES", name.to_uppercase());
                code.push_str(&format!(
                    "static {bytes_static}: &[u8] = include_bytes!(\"{}\");\n",
                    wasm_path.display()
                ));
                entries.push_str(&format!(
                    "    BundledAsset {{\n        name: \"{name}\",\n        display_name: \"{display_name}\",\n        version: \"{version}\",\n        bytes: {bytes_static},\n        category: AssetCategory::{kind},\n    }},\n",
                ));
            } else {
                missing(&wasm_path, kind, name);
            }
        }
        code.push_str(&format!(
            "\n/// Bundled {} assets\npub static {array_name}: &[BundledAsset] = &[\n{entries}];\n\n",
            kind.to_lowercase()
        ));
    };

    emit("Model", "crates/models", MODELS, include_models);
    emit("Operator", "crates/operators", OPERATORS, include_operators);

    // Write generated code
    let out_path = out_dir.join("asset_registry.rs");
    fs::write(&out_path, code).expect("Failed to write asset_registry.rs");

    // Rerun if the wasm directory changes
    println!("cargo:rerun-if-changed={}", wasm_dir.display());
}
