//! Build script to generate the asset registry by scanning for WASM files.
//!
//! This scans `target/wasm32-unknown-unknown/release/` for known model and operator
//! WASM files and generates Rust code that embeds them using `include_bytes!()`.

use sha2::{Digest, Sha256};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// Known model crate names. Display metadata (names, descriptions,
/// categories, icons) is NOT recorded here: every module declares its own
/// through `get_metadata()`, and hosts read it from the bytes.
const MODELS: &[&str] = &[
    "simple_sphere_model",
    "simple_torus_model",
    "rounded_box_model",
    "gyroid_lattice_model",
    "mandelbulb_model",
    "density_gradient_model",
];

/// Known operator crate names (see the display-metadata note on [`MODELS`]).
const OPERATORS: &[&str] = &[
    "boolean_operator",
    "translate_operator",
    "rotation_operator",
    "scale_operator",
    "lua_script_operator",
    "f64_map_merge_operator",
    "stl_import_operator",
    "rectangular_prism_operator",
    "heightmap_extrude_operator",
    "image_model_operator",
    "extrude_operator",
    "revolve_operator",
    "fea_grid_mesh_operator",
    "fea_solve_operator",
    "fea_density_operator",
    "fea_inverse_operator",
    "fea_deform_operator",
    "mesh_to_model_operator",
    "mesh_height_operator",
    "lattice_operator",
    "strut_pattern_operator",
    "strut_model_operator",
    "brim_operator",
    "island_removal_operator",
    "sdf_operator",
    "subspace_operator",
    "subspace_fit_operator",
    "model_bound_operator",
    "slice_operator",
    "span_operator",
    "intersect_operator",
];

/// Reads `version = "..."` from a bundled crate's Cargo.toml. Every bundled
/// asset declares `version: env!("CARGO_PKG_VERSION")` in its metadata, so
/// the manifest version IS the declared metadata version — bundling it lets
/// consumers (e.g. the UI's upgrade offer) know bundled versions without
/// compiling the wasm modules at runtime.
fn crate_version(crate_dir: &std::path::Path) -> String {
    let manifest = crate_dir.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let text = fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest.display()));
    text.lines()
        .find_map(|line| {
            line.strip_prefix("version")?
                .trim_start()
                .strip_prefix('=')?
                .trim()
                .strip_prefix('"')?
                .strip_suffix('"')
                .map(str::to_string)
        })
        .unwrap_or_else(|| panic!("no version in {}", manifest.display()))
}

/// Hex SHA-256 of `bytes` — the content hash bundled into each registry entry
/// so hosts can spot a project's stale embedded copy without recompiling wasm.
fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(64);
    for byte in digest {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

/// Reports a missing wasm artifact. Normally a warning (dev builds often
/// don't need the bundle — tests, check builds), but release packaging must
/// not silently ship an empty library: with VOLUMETRIC_ASSETS_REQUIRE set
/// (the daemon Containerfile sets it), a missing file fails the build.
fn missing(wasm_path: &std::path::Path, kind: &str, name: &str) {
    if env::var_os("VOLUMETRIC_ASSETS_REQUIRE").is_some() {
        panic!(
            "{kind} '{name}' not found at {} but VOLUMETRIC_ASSETS_REQUIRE is set — run `cargo build-wasm` first",
            wasm_path.display()
        );
    }
    println!(
        "cargo:warning=WASM file not found: {}. {kind} '{name}' will not be bundled.",
        wasm_path.display()
    );
}

fn main() {
    println!("cargo:rerun-if-env-changed=VOLUMETRIC_ASSETS_REQUIRE");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // The workspace root is two levels up from crates/volumetric_assets
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let wasm_dir = workspace_root
        .join("target")
        .join("wasm32-unknown-unknown")
        .join("release");

    let include_models = env::var("CARGO_FEATURE_MODELS").is_ok();
    let include_operators = env::var("CARGO_FEATURE_OPERATORS").is_ok();

    let mut code = String::new();

    // Generate model constants
    code.push_str("// Auto-generated by build.rs - do not edit\n\n");

    // Everything here is `static`, never `const`: a const's promoted
    // allocation is materialized at every use site, so `const` registries
    // duplicated every include_bytes!() blob once per referencing function
    // (measured: +73MB on the web bundle — the whole 36.5MB library twice).
    let mut emit = |kind: &str, subdir: &str, list: &[&str], enabled: bool| {
        let array_name = format!("BUNDLED_{}S", kind.to_uppercase());
        if !enabled {
            code.push_str(&format!(
                "/// Bundled {} assets (disabled)\npub static {array_name}: &[BundledAsset] = &[];\n\n",
                kind.to_lowercase()
            ));
            return;
        }
        let mut entries = String::new();
        for name in list {
            let wasm_path = wasm_dir.join(format!("{}.wasm", name));
            if wasm_path.exists() {
                println!("cargo:rerun-if-changed={}", wasm_path.display());
                let version = crate_version(&workspace_root.join(subdir).join(name));
                let bytes = fs::read(&wasm_path)
                    .unwrap_or_else(|e| panic!("read {}: {e}", wasm_path.display()));
                let hash = sha256_hex(&bytes);
                let bytes_static = format!("{}_BYTES", name.to_uppercase());
                code.push_str(&format!(
                    "static {bytes_static}: &[u8] = include_bytes!(\"{}\");\n",
                    wasm_path.display()
                ));
                entries.push_str(&format!(
                    "    BundledAsset {{\n        name: \"{name}\",\n        version: \"{version}\",\n        hash: \"{hash}\",\n        bytes: {bytes_static},\n        category: AssetCategory::{kind},\n    }},\n",
                ));
            } else {
                missing(&wasm_path, kind, name);
            }
        }
        code.push_str(&format!(
            "\n/// Bundled {} assets\npub static {array_name}: &[BundledAsset] = &[\n{entries}];\n\n",
            kind.to_lowercase()
        ));
    };

    emit("Model", "crates/models", MODELS, include_models);
    emit("Operator", "crates/operators", OPERATORS, include_operators);

    // Write generated code
    let out_path = out_dir.join("asset_registry.rs");
    fs::write(&out_path, code).expect("Failed to write asset_registry.rs");

    // Rerun if the wasm directory changes
    println!("cargo:rerun-if-changed={}", wasm_dir.display());
}
